name: Release

on:
  push:
    branches: [stable]
    tags:    ['v*']
  workflow_dispatch: {}

permissions:
  contents: write
  id-token: write

jobs:
  # build the program on windows and linux
  build:
    uses: ./.github/workflows/build.yml # just calls build.yml to reduce repitition

  # creates a draft release to be edited
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository so that cliff.toml is available
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    # fetch built binaries
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: rumm-*
        merge-multiple: true
        path: dist
    # generate changelog
    - name: Generate changelog
      id: cliff
      uses: orhun/git-cliff-action@v3
      with:
        config: .github/cliff.toml
        args: --latest --output CHANGELOG.md
    # make the actual release
    - name: Draft GitHub release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        body_path: CHANGELOG.md
        files: dist/**